<?php

/**
 * @file
 * Contains migrate_nidirect_utils.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function migrate_nidirect_utils_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the migrate_nidirect_utils module.
    case 'help.page.migrate_nidirect_utils':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Utilities and tools for working with migrations') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements template_preprocess_page_title().
 */
function migrate_nidirect_utils_node_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  $x = 1;
  $data_json = 'a:1:{s:8:"keywords";a:1:{s:5:"value";s:5:"groni";}}';
  $data_json2 = 'a:1:{s:8:';
  $data = json_decode($data_json);
}


