<?php

/**
 * @file
 * Contains migrate_nidirect_utils.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function migrate_nidirect_utils_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the migrate_nidirect_utils module.
    case 'help.page.migrate_nidirect_utils':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Utilities and tools for working with migrations') . '</p>';
      return $output;

    default:
  }
}


