name: 'Migrate NIDirect - Node:Application'
type: module
description: 'NIDirect migration Application content type'
core_version_requirement: ^8.8 || ^9
package: 'Migrate NIDirect'
migration_dependencies:
 required: { }
dependencies:
  - drupal:migrate
  - drupal:migrate_plus
  - drupal:migrate_tools
