<?php

use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Row;

/**
 * Implements hook_migrate_MIGRATION_ID_prepare_row().
 */
function migrate_nidirect_node_application_migrate_node_application_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {

  $body_field = $row->getSourceProperty('body');
  $body_field[0]['value'] = '<h2>Before you start</h2>' . $body_field[0]['value'];
  $row->setSourceProperty('body', $body_field);

  $addinfo_field = $row->getSourceProperty('field_additional_info');
  $addinfo_field[0]['value'] = '<h2>Additional information</h2>' . $addinfo_field[0]['value'];
  $row->setSourceProperty('field_additional_info', $addinfo_field);
}
