<?php

/**
 * @file
 * Contains migrate_nidirect_node_application.module.
 */

use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Row;

/**
 * Implements hook_migrate_MIGRATION_ID_prepare_row().
 */
function migrate_nidirect_node_application_migrate_node_application_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  _process_application_row($row);
}

/**
 * Implements hook_migrate_MIGRATION_ID_prepare_row().
 */
function migrate_nidirect_node_application_migrate_node_revision_application_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  _process_application_row($row);
}

/**
 * Injects heading text into body and additional info fields.
 *
 * @param \Drupal\migrate\Row $row
 *   Migration row.
 */
function _process_application_row(Row &$row) {
  // Add a title to the body field.
  $body_field = $row->getSourceProperty('body');

  // Inject the title if the field has content and that content contains words.
  // Checking the value has at least 1 vowel to prevent processing of
  // &nbsp; etc.
  if (!empty($body_field[0]['value']) && preg_match('/[aeiou]/m', $body_field[0]['value'])) {
    $body_field[0]['value'] = '<h2>Before you start</h2>' . $body_field[0]['value'];
    $row->setSourceProperty('body', $body_field);
  }

  // Add a title to the additional info field.
  $addinfo_field = $row->getSourceProperty('field_additional_info');

  // Inject the title if the field has content and that content contains words.
  // Checking the value has at least 1 vowel to prevent processing of
  // &nbsp; etc.
  if (!empty($addinfo_field[0]['value']) && preg_match('/[aeiou]/m', $addinfo_field[0]['value'])) {
    // Only insert a title of the content doesn't start with an <h2> title
    // element.
    if (preg_match('/^<h2>...+<\/h2>/m', $addinfo_field[0]['value']) === 0) {
      $addinfo_field[0]['value'] = '<h2>Additional information</h2>' . $addinfo_field[0]['value'];
      $row->setSourceProperty('field_additional_info', $addinfo_field);
    }
  }
}
