<?php

/**
 * @file
 * Contains migrate_nidirect.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function migrate_nidirect_file_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the migrate_nidirect_file module.
    case 'help.page.migrate_nidirect_file':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('NIDirect migrations') . '</p>';
      return $output;

    default:
  }
}
